from django.conf.urls.defaults import *

# EECS 398 students: the comments in this file are automatically
# generated by Django; we've left them in just in case. You should NOT
# need to fill in anything in this file.

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'search398.simplesearch.views.index'),
    (r'^search', 'search398.simplesearch.views.search'),
    (r'^login', 'search398.simplesearch.views.login'),
    (r'^logout', 'search398.simplesearch.views.logout'),
    (r'^attack', 'search398.simplesearch.views.attack')	
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/(.*)', admin.site.root),
)
